platform :ios, '11.0'

workspace 'app.xcworkspace'

target 'BECS Debit Example (Swift)' do
  project 'BECS Debit Example (Swift)/BECS Debit Example (Swift).xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :commit => 'a14410f'
end

target 'BECS Debit Example (ObjC)' do
  project 'BECS Debit Example (ObjC)/BECS Debit Example (ObjC).xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :commit => 'a14410f'
end

